### ISSUE TITLE
Imports in test_estimation

### ISSUE THREAD

**Issue by jonathan-taylor** [selective-inference/Python-software#21]
Tries to call "selection" and "estimation" function without importing them.

**Comment by jonathan-taylor** [comment]
======================================================================
ERROR: selection.randomized.tests.test_estimation.test_MSE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathantaylor/anaconda/envs/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jonathantaylor/git-repos/selection/selection/randomized/tests/test_estimation.py", line 18, in test_MSE
    lam, epsilon, active, betaE, cube, initial_soln = selection(X, y, random_Z) # selection not defined -- is in a file that was deleted
NameError: global name 'selection' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.061s
